# Generated by Django 5.2.1 on 2025-05-13 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='description',
        ),
        migrations.AddField(
            model_name='publisher',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='publisher_logos/'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='subscribers',
            field=models.ManyToManyField(blank=True, help_text='Users who subscribed to this publisher.', related_name='subscribed_publishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='Users with the Editor role.', related_name='editor_of_publishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='journalists',
            field=models.ManyToManyField(blank=True, help_text='Users with the Journalist role.', related_name='journalist_of_publishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('READER', 'Reader'), ('JOURNALIST', 'Journalist'), ('PUBLISHER', 'Publisher')], default='READER', help_text='Defines the role of the user: Reader, Journalist, or Editor.', max_length=10),
        ),
    ]
