# Generated by Django 5.2.1 on 2025-05-13 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_publisher_description_publisher_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
