# Generated by Django 5.2.1 on 2025-05-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_publisher_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='content',
        ),
    ]
