# Generated by Django 5.2.1 on 2025-05-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_body_article_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='body',
        ),
    ]
