# Generated by Django 5.2.1 on 2025-05-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_content_article_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='content',
            new_name='body',
        ),
    ]
